spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    时区
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
    username: root
    password: 28465
#    设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
